name: Build DERPER

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build DERPER
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # 创建构建目录
          mkdir -p build

          # 获取最新的 derper 代码
          go get tailscale.com/cmd/derper@latest

          # 确定输出文件名
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTPUT="build/derper-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
          else
            OUTPUT="build/derper-${{ matrix.goos }}-${{ matrix.goarch }}"
          fi

          # 直接构建到目标文件
          go build -o $OUTPUT tailscale.com/cmd/derper

          # 显示构建结果
          ls -la build/
          file build/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: derper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/derper-*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/derper-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
