name: Build DERPER

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build DERPER
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go install tailscale.com/cmd/derper@latest
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            cp $(go env GOPATH)/bin/derper.exe dist/derper-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          else
            cp $(go env GOPATH)/bin/derper dist/derper-${{ matrix.goos }}-${{ matrix.goarch }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: derper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
